using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StringBuilderApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Construct a sentence with me in 3 parts!"); //Requests the user for some arbitrary text
            Console.WriteLine("Line one:"); //Gathers 3 lines generated by the user.
            string line1 = Console.ReadLine();
            Console.WriteLine("Line two:");
            string line2 = Console.ReadLine();
            Console.WriteLine("Line three:");
            string line3 = Console.ReadLine();

            //Builds the sentence

            string sentence = line1 + " " + line2 + " " + line3; //Concatenates the three lines of the users choosing
            Console.WriteLine("Lets see what we made!");
            Console.WriteLine(sentence); //Displays the concatenated lines that were formed into the variable sentence.
            Console.ReadLine();

            Console.WriteLine("Now in uppercase!"); //This section capitalizes the entire sentence and displays it.
            Console.WriteLine(sentence.ToUpper());
            Console.ReadLine();

            Console.WriteLine("Lets build a 4 sentence paragraph now!"); //This section uses stringbuilder to build a paragraph.

            StringBuilder sb = new StringBuilder(); //Creates a stringbuilder that constructs a sentence with the four inputs below.
            Console.WriteLine("Write your first sentence.");
            sb.Append(Console.ReadLine());

            Console.WriteLine("Write your second sentence."); //Each line inputted into the stringbuilder is concatenated with a space to create a clean paragraph.
            sb.Append(" " + Console.ReadLine());

            Console.WriteLine("Write your third sentence."); 
            sb.Append(" "  + Console.ReadLine());

            Console.WriteLine("Write your fourth sentence.");
            sb.Append(" " + Console.ReadLine());


            Console.WriteLine(sb); //Displays the completed sentence
            Console.ReadLine();


        }
    }
}
